# Generated by Django 5.1.1 on 2024-10-05 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
