# Generated by Django 5.1.1 on 2024-10-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseApp", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="places/")),
                ("construction_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
